--
-- PostgreSQL database dump
--

-- Dumped from database version 10.8
-- Dumped by pg_dump version 11.2

-- Started on 2020-11-13 21:13:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3162 (class 1262 OID 69571)
-- Name: facultades; Type: DATABASE; Schema: -; Owner: postgres
--


ALTER DATABASE facultades OWNER TO postgres;


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 69577)
-- Name: bdARemplazar; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA IF NOT EXISTS bdARemplazar;


ALTER SCHEMA bdARemplazar OWNER TO postgres;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 236 (class 1259 OID 69886)
-- Name: Calificaciones; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Calificaciones" (
    "Id" integer NOT NULL,
    "Nota" integer NOT NULL,
    "FechaPublicada" timestamp without time zone NOT NULL,
    "FechaCorregida" timestamp without time zone NOT NULL,
    "EstadoCalificacion" text,
    "EstudianteId" integer NOT NULL,
    "EvaluacionId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Calificaciones" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 69884)
-- Name: Calificaciones_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Calificaciones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Calificaciones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 69652)
-- Name: Chats; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Chats" (
    "Id" integer NOT NULL,
    "PersonaId1" integer NOT NULL,
    "Persona1Id" integer,
    "PersonaId2" integer NOT NULL,
    "Persona2Id" integer
);


ALTER TABLE bdARemplazar."Chats" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 69650)
-- Name: Chats_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Chats" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Chats_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 69951)
-- Name: Comentarios; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Comentarios" (
    "Id" integer NOT NULL,
    "FechaCreado" timestamp without time zone NOT NULL,
    "Texto" text NOT NULL,
    "CuentaId" integer NOT NULL,
    "DiscusionId" integer NOT NULL,
    "ComentarioId" integer
);


ALTER TABLE bdARemplazar."Comentarios" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 69949)
-- Name: Comentarios_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Comentarios" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Comentarios_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 69801)
-- Name: ComunicadoCurso; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."ComunicadoCurso" (
    "Id" integer NOT NULL,
    "Titulo" text,
    "Texto" text,
    "FechaPublicacion" timestamp without time zone NOT NULL,
    "CursoId" integer NOT NULL,
    "DocenteId" integer NOT NULL
);


ALTER TABLE bdARemplazar."ComunicadoCurso" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 69799)
-- Name: ComunicadoCurso_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."ComunicadoCurso" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."ComunicadoCurso_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 69669)
-- Name: Cuenta; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Cuenta" (
    "Id" integer NOT NULL,
    "Usuario" text NOT NULL,
    "Passwd" text,
    "Salt" text,
    "Email" text NOT NULL,
    "NumeroTelefono" text,
    "TipoCuenta" text,
    "PersonaId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Cuenta" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 69821)
-- Name: CuentaGoogle; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."CuentaGoogle" (
    "Id" integer NOT NULL,
    "GoogleId" text,
    "ImgUrl" text,
    "CuentaId" integer NOT NULL
);


ALTER TABLE bdARemplazar."CuentaGoogle" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 69819)
-- Name: CuentaGoogle_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."CuentaGoogle" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."CuentaGoogle_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 69667)
-- Name: Cuenta_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Cuenta" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Cuenta_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 199 (class 1259 OID 69580)
-- Name: Curso; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Curso" (
    "Id" integer NOT NULL,
    "Nombre" text,
    "Creditos" integer NOT NULL,
    "ClaveMatriculacion" text,
    "YearDiactado" integer NOT NULL,
    "TipoCurso" text,
    "DictaCurso" text,
    "Informacion" text,
    "FechaLimiteInscripcion" timestamp without time zone NOT NULL,
    "NotaMinimaAprobacion" integer NOT NULL,
    "NotaMaximaAprobacion" integer NOT NULL,
    "NotaMinimaExamen" integer,
    "NotaMaximaExamen" integer
);


ALTER TABLE bdARemplazar."Curso" OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 69578)
-- Name: Curso_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Curso" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Curso_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 69906)
-- Name: Desarrollo; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Desarrollo" (
    "Id" integer NOT NULL,
    "Pregunta" text,
    "PuntajeAprobacion" integer NOT NULL,
    "EvaluacionId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Desarrollo" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 69904)
-- Name: Desarrollo_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Desarrollo" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Desarrollo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 69836)
-- Name: Discusiones; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Discusiones" (
    "Id" integer NOT NULL,
    "Titulo" text NOT NULL,
    "FechaCreado" timestamp without time zone NOT NULL,
    "CuentaId" integer NOT NULL,
    "ForoId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Discusiones" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 69834)
-- Name: Discusiones_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Discusiones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Discusiones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 69854)
-- Name: DocentesCurso; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."DocentesCurso" (
    "DocenteId" integer NOT NULL,
    "CursoId" integer NOT NULL,
    "Escargado" boolean NOT NULL
);


ALTER TABLE bdARemplazar."DocentesCurso" OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 69590)
-- Name: Encuesta; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Encuesta" (
    "Id" integer NOT NULL,
    "Titulo" text,
    "Fecha" timestamp without time zone NOT NULL,
    "TipoEncuesta" text
);


ALTER TABLE bdARemplazar."Encuesta" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 69699)
-- Name: EncuestaCurso; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."EncuestaCurso" (
    "EncuestaId" integer NOT NULL,
    "SeccionTemplateId" integer NOT NULL,
    "CursoId" integer NOT NULL
);


ALTER TABLE bdARemplazar."EncuestaCurso" OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 69588)
-- Name: Encuesta_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Encuesta" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Encuesta_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 69721)
-- Name: Evaluaciones; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Evaluaciones" (
    "Id" integer NOT NULL,
    "Titulo" text,
    "Fecha" timestamp without time zone NOT NULL,
    "ValidacionBedelia" boolean NOT NULL,
    "Publicada" boolean NOT NULL,
    "TipoEvaluacion" text,
    "CalificacionAprobacion" integer NOT NULL,
    "SeccionTemplateId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Evaluaciones" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 69719)
-- Name: Evaluaciones_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Evaluaciones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Evaluaciones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 69600)
-- Name: Foros; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Foros" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL
);


ALTER TABLE bdARemplazar."Foros" OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 69598)
-- Name: Foros_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Foros" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Foros_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 69736)
-- Name: Informacion; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Informacion" (
    "Id" integer NOT NULL,
    "Titulo" text,
    "Descripcion" text,
    "Fecha" timestamp without time zone NOT NULL,
    "SeccionTemplateId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Informacion" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 69734)
-- Name: Informacion_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Informacion" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Informacion_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 69869)
-- Name: Inscripcion; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Inscripcion" (
    "CursoId" integer NOT NULL,
    "EsudianteInscripcionId" integer NOT NULL,
    "FechaInscripcion" timestamp without time zone NOT NULL,
    "HabilitadoBedelia" boolean,
    "Metriculado" boolean NOT NULL
);


ALTER TABLE bdARemplazar."Inscripcion" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 69751)
-- Name: Material; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Material" (
    "Id" integer NOT NULL,
    "Nombre" text,
    "Url" text,
    "SeccionId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Material" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 69749)
-- Name: Material_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Material" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Material_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 69781)
-- Name: Mensajes; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Mensajes" (
    "Id" integer NOT NULL,
    "FechaEnvio" timestamp without time zone NOT NULL,
    "Texto" text NOT NULL,
    "EnviadoPor" integer NOT NULL,
    "PersonaId" integer,
    "ChatId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Mensajes" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 69779)
-- Name: Mensajes_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Mensajes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Mensajes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 69686)
-- Name: Notificaciones; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Notificaciones" (
    "Id" integer NOT NULL,
    "FechaCreada" timestamp without time zone NOT NULL,
    "Titulo" text NOT NULL,
    "Mensaje" text NOT NULL,
    "PersonaId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Notificaciones" OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 69684)
-- Name: Notificaciones_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Notificaciones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Notificaciones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 69766)
-- Name: Opciones; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Opciones" (
    "Id" integer NOT NULL,
    "Respuesta" text,
    "PreguntaId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Opciones" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 69996)
-- Name: OpcionesVoF; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."OpcionesVoF" (
    "Id" integer NOT NULL,
    "Frase" text,
    "Correcta" boolean NOT NULL,
    "VerdaderoFalsoId" integer NOT NULL
);


ALTER TABLE bdARemplazar."OpcionesVoF" OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 69994)
-- Name: OpcionesVoF_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."OpcionesVoF" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."OpcionesVoF_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 69764)
-- Name: Opciones_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Opciones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Opciones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 69610)
-- Name: Persona; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Persona" (
    "Id" integer NOT NULL,
    "Ci" integer NOT NULL,
    "Nombre" text,
    "Apellido" text
);


ALTER TABLE bdARemplazar."Persona" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 69608)
-- Name: Persona_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Persona" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Persona_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 69637)
-- Name: Preguntas; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Preguntas" (
    "Id" integer NOT NULL,
    "Frase" text,
    "TipoCheck" text,
    "EncuestaId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Preguntas" OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 69635)
-- Name: Preguntas_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."Preguntas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."Preguntas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 69976)
-- Name: RespuestaDesarrollo; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."RespuestaDesarrollo" (
    "Id" integer NOT NULL,
    "Respuesta" text,
    "Puntaje" integer NOT NULL,
    "EstudianteId" integer NOT NULL,
    "DesarrolloId" integer NOT NULL
);


ALTER TABLE bdARemplazar."RespuestaDesarrollo" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 69974)
-- Name: RespuestaDesarrollo_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."RespuestaDesarrollo" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."RespuestaDesarrollo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 70011)
-- Name: RespuestaVoF; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."RespuestaVoF" (
    "Id" integer NOT NULL,
    "Eleccion" boolean NOT NULL,
    "EstudianteId" integer NOT NULL,
    "OpcionId" integer NOT NULL,
    "VerdaderoFalsoId" integer NOT NULL
);


ALTER TABLE bdARemplazar."RespuestaVoF" OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 70009)
-- Name: RespuestaVoF_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."RespuestaVoF" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."RespuestaVoF_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 69934)
-- Name: Respuestas; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."Respuestas" (
    "OpcionId" integer NOT NULL,
    "CuentaId" integer NOT NULL
);


ALTER TABLE bdARemplazar."Respuestas" OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 69622)
-- Name: SeccionTemplate; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."SeccionTemplate" (
    "Id" integer NOT NULL,
    "Titulo" text,
    "Visible" boolean NOT NULL,
    "Prioridad" integer NOT NULL,
    "CursoId" integer NOT NULL
);


ALTER TABLE bdARemplazar."SeccionTemplate" OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 69620)
-- Name: SeccionTemplate_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."SeccionTemplate" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."SeccionTemplate_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 69921)
-- Name: VerdaderoFalso; Type: TABLE; Schema: bdARemplazar; Owner: postgres
--

CREATE TABLE bdARemplazar."VerdaderoFalso" (
    "Id" integer NOT NULL,
    "Frase" text,
    "MultipleOpcion" boolean NOT NULL,
    "EvaluacionId" integer NOT NULL
);


ALTER TABLE bdARemplazar."VerdaderoFalso" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 69919)
-- Name: VerdaderoFalso_Id_seq; Type: SEQUENCE; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE bdARemplazar."VerdaderoFalso" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bdARemplazar."VerdaderoFalso_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3143 (class 0 OID 69886)
-- Dependencies: 236
-- Data for Name: Calificaciones; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3118 (class 0 OID 69652)
-- Dependencies: 211
-- Data for Name: Chats; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3150 (class 0 OID 69951)
-- Dependencies: 243
-- Data for Name: Comentarios; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3135 (class 0 OID 69801)
-- Dependencies: 228
-- Data for Name: ComunicadoCurso; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3120 (class 0 OID 69669)
-- Dependencies: 213
-- Data for Name: Cuenta; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3137 (class 0 OID 69821)
-- Dependencies: 230
-- Data for Name: CuentaGoogle; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3106 (class 0 OID 69580)
-- Dependencies: 199
-- Data for Name: Curso; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3145 (class 0 OID 69906)
-- Dependencies: 238
-- Data for Name: Desarrollo; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3139 (class 0 OID 69836)
-- Dependencies: 232
-- Data for Name: Discusiones; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3140 (class 0 OID 69854)
-- Dependencies: 233
-- Data for Name: DocentesCurso; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3108 (class 0 OID 69590)
-- Dependencies: 201
-- Data for Name: Encuesta; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3123 (class 0 OID 69699)
-- Dependencies: 216
-- Data for Name: EncuestaCurso; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3125 (class 0 OID 69721)
-- Dependencies: 218
-- Data for Name: Evaluaciones; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3110 (class 0 OID 69600)
-- Dependencies: 203
-- Data for Name: Foros; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3127 (class 0 OID 69736)
-- Dependencies: 220
-- Data for Name: Informacion; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3141 (class 0 OID 69869)
-- Dependencies: 234
-- Data for Name: Inscripcion; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3129 (class 0 OID 69751)
-- Dependencies: 222
-- Data for Name: Material; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3133 (class 0 OID 69781)
-- Dependencies: 226
-- Data for Name: Mensajes; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3122 (class 0 OID 69686)
-- Dependencies: 215
-- Data for Name: Notificaciones; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3131 (class 0 OID 69766)
-- Dependencies: 224
-- Data for Name: Opciones; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3154 (class 0 OID 69996)
-- Dependencies: 247
-- Data for Name: OpcionesVoF; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3112 (class 0 OID 69610)
-- Dependencies: 205
-- Data for Name: Persona; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3116 (class 0 OID 69637)
-- Dependencies: 209
-- Data for Name: Preguntas; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3152 (class 0 OID 69976)
-- Dependencies: 245
-- Data for Name: RespuestaDesarrollo; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3156 (class 0 OID 70011)
-- Dependencies: 249
-- Data for Name: RespuestaVoF; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3148 (class 0 OID 69934)
-- Dependencies: 241
-- Data for Name: Respuestas; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3114 (class 0 OID 69622)
-- Dependencies: 207
-- Data for Name: SeccionTemplate; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3147 (class 0 OID 69921)
-- Dependencies: 240
-- Data for Name: VerdaderoFalso; Type: TABLE DATA; Schema: bdARemplazar; Owner: postgres
--



--
-- TOC entry 3163 (class 0 OID 0)
-- Dependencies: 235
-- Name: Calificaciones_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Calificaciones_Id_seq"', 1, false);


--
-- TOC entry 3164 (class 0 OID 0)
-- Dependencies: 210
-- Name: Chats_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Chats_Id_seq"', 1, false);


--
-- TOC entry 3165 (class 0 OID 0)
-- Dependencies: 242
-- Name: Comentarios_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Comentarios_Id_seq"', 1, false);


--
-- TOC entry 3166 (class 0 OID 0)
-- Dependencies: 227
-- Name: ComunicadoCurso_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."ComunicadoCurso_Id_seq"', 1, false);


--
-- TOC entry 3167 (class 0 OID 0)
-- Dependencies: 229
-- Name: CuentaGoogle_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."CuentaGoogle_Id_seq"', 1, false);


--
-- TOC entry 3168 (class 0 OID 0)
-- Dependencies: 212
-- Name: Cuenta_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Cuenta_Id_seq"', 1, false);


--
-- TOC entry 3169 (class 0 OID 0)
-- Dependencies: 198
-- Name: Curso_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Curso_Id_seq"', 1, false);


--
-- TOC entry 3170 (class 0 OID 0)
-- Dependencies: 237
-- Name: Desarrollo_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Desarrollo_Id_seq"', 1, false);


--
-- TOC entry 3171 (class 0 OID 0)
-- Dependencies: 231
-- Name: Discusiones_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Discusiones_Id_seq"', 1, false);


--
-- TOC entry 3172 (class 0 OID 0)
-- Dependencies: 200
-- Name: Encuesta_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Encuesta_Id_seq"', 1, false);


--
-- TOC entry 3173 (class 0 OID 0)
-- Dependencies: 217
-- Name: Evaluaciones_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Evaluaciones_Id_seq"', 1, false);


--
-- TOC entry 3174 (class 0 OID 0)
-- Dependencies: 202
-- Name: Foros_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Foros_Id_seq"', 1, false);


--
-- TOC entry 3175 (class 0 OID 0)
-- Dependencies: 219
-- Name: Informacion_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Informacion_Id_seq"', 1, false);


--
-- TOC entry 3176 (class 0 OID 0)
-- Dependencies: 221
-- Name: Material_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Material_Id_seq"', 1, false);


--
-- TOC entry 3177 (class 0 OID 0)
-- Dependencies: 225
-- Name: Mensajes_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Mensajes_Id_seq"', 1, false);


--
-- TOC entry 3178 (class 0 OID 0)
-- Dependencies: 214
-- Name: Notificaciones_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Notificaciones_Id_seq"', 1, false);


--
-- TOC entry 3179 (class 0 OID 0)
-- Dependencies: 246
-- Name: OpcionesVoF_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."OpcionesVoF_Id_seq"', 1, false);


--
-- TOC entry 3180 (class 0 OID 0)
-- Dependencies: 223
-- Name: Opciones_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Opciones_Id_seq"', 1, false);


--
-- TOC entry 3181 (class 0 OID 0)
-- Dependencies: 204
-- Name: Persona_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Persona_Id_seq"', 1, false);


--
-- TOC entry 3182 (class 0 OID 0)
-- Dependencies: 208
-- Name: Preguntas_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."Preguntas_Id_seq"', 1, false);


--
-- TOC entry 3183 (class 0 OID 0)
-- Dependencies: 244
-- Name: RespuestaDesarrollo_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."RespuestaDesarrollo_Id_seq"', 1, false);


--
-- TOC entry 3184 (class 0 OID 0)
-- Dependencies: 248
-- Name: RespuestaVoF_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."RespuestaVoF_Id_seq"', 1, false);


--
-- TOC entry 3185 (class 0 OID 0)
-- Dependencies: 206
-- Name: SeccionTemplate_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."SeccionTemplate_Id_seq"', 1, false);


--
-- TOC entry 3186 (class 0 OID 0)
-- Dependencies: 239
-- Name: VerdaderoFalso_Id_seq; Type: SEQUENCE SET; Schema: bdARemplazar; Owner: postgres
--

SELECT pg_catalog.setval('bdARemplazar."VerdaderoFalso_Id_seq"', 1, false);


--
-- TOC entry 2871 (class 2606 OID 69678)
-- Name: Cuenta AK_Cuenta_Usuario_Email; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Cuenta"
    ADD CONSTRAINT "AK_Cuenta_Usuario_Email" UNIQUE ("Usuario", "Email");


--
-- TOC entry 2857 (class 2606 OID 69619)
-- Name: Persona AK_Persona_Ci; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Persona"
    ADD CONSTRAINT "AK_Persona_Ci" UNIQUE ("Ci");


--
-- TOC entry 2918 (class 2606 OID 69893)
-- Name: Calificaciones PK_Calificaciones; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Calificaciones"
    ADD CONSTRAINT "PK_Calificaciones" PRIMARY KEY ("Id");


--
-- TOC entry 2869 (class 2606 OID 69656)
-- Name: Chats PK_Chats; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Chats"
    ADD CONSTRAINT "PK_Chats" PRIMARY KEY ("Id");


--
-- TOC entry 2932 (class 2606 OID 69958)
-- Name: Comentarios PK_Comentarios; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Comentarios"
    ADD CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id");


--
-- TOC entry 2901 (class 2606 OID 69808)
-- Name: ComunicadoCurso PK_ComunicadoCurso; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."ComunicadoCurso"
    ADD CONSTRAINT "PK_ComunicadoCurso" PRIMARY KEY ("Id");


--
-- TOC entry 2874 (class 2606 OID 69676)
-- Name: Cuenta PK_Cuenta; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Cuenta"
    ADD CONSTRAINT "PK_Cuenta" PRIMARY KEY ("Id");


--
-- TOC entry 2904 (class 2606 OID 69828)
-- Name: CuentaGoogle PK_CuentaGoogle; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."CuentaGoogle"
    ADD CONSTRAINT "PK_CuentaGoogle" PRIMARY KEY ("Id");


--
-- TOC entry 2851 (class 2606 OID 69587)
-- Name: Curso PK_Curso; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Curso"
    ADD CONSTRAINT "PK_Curso" PRIMARY KEY ("Id");


--
-- TOC entry 2921 (class 2606 OID 69913)
-- Name: Desarrollo PK_Desarrollo; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Desarrollo"
    ADD CONSTRAINT "PK_Desarrollo" PRIMARY KEY ("Id");


--
-- TOC entry 2908 (class 2606 OID 69843)
-- Name: Discusiones PK_Discusiones; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Discusiones"
    ADD CONSTRAINT "PK_Discusiones" PRIMARY KEY ("Id");


--
-- TOC entry 2911 (class 2606 OID 69858)
-- Name: DocentesCurso PK_DocentesCurso; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."DocentesCurso"
    ADD CONSTRAINT "PK_DocentesCurso" PRIMARY KEY ("CursoId", "DocenteId");


--
-- TOC entry 2853 (class 2606 OID 69597)
-- Name: Encuesta PK_Encuesta; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Encuesta"
    ADD CONSTRAINT "PK_Encuesta" PRIMARY KEY ("Id");


--
-- TOC entry 2881 (class 2606 OID 69703)
-- Name: EncuestaCurso PK_EncuestaCurso; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."EncuestaCurso"
    ADD CONSTRAINT "PK_EncuestaCurso" PRIMARY KEY ("SeccionTemplateId", "EncuestaId");


--
-- TOC entry 2884 (class 2606 OID 69728)
-- Name: Evaluaciones PK_Evaluaciones; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Evaluaciones"
    ADD CONSTRAINT "PK_Evaluaciones" PRIMARY KEY ("Id");


--
-- TOC entry 2855 (class 2606 OID 69607)
-- Name: Foros PK_Foros; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Foros"
    ADD CONSTRAINT "PK_Foros" PRIMARY KEY ("Id");


--
-- TOC entry 2887 (class 2606 OID 69743)
-- Name: Informacion PK_Informacion; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Informacion"
    ADD CONSTRAINT "PK_Informacion" PRIMARY KEY ("Id");


--
-- TOC entry 2914 (class 2606 OID 69873)
-- Name: Inscripcion PK_Inscripcion; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Inscripcion"
    ADD CONSTRAINT "PK_Inscripcion" PRIMARY KEY ("CursoId", "EsudianteInscripcionId");


--
-- TOC entry 2890 (class 2606 OID 69758)
-- Name: Material PK_Material; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Material"
    ADD CONSTRAINT "PK_Material" PRIMARY KEY ("Id");


--
-- TOC entry 2897 (class 2606 OID 69788)
-- Name: Mensajes PK_Mensajes; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Mensajes"
    ADD CONSTRAINT "PK_Mensajes" PRIMARY KEY ("Id");


--
-- TOC entry 2877 (class 2606 OID 69693)
-- Name: Notificaciones PK_Notificaciones; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Notificaciones"
    ADD CONSTRAINT "PK_Notificaciones" PRIMARY KEY ("Id");


--
-- TOC entry 2893 (class 2606 OID 69773)
-- Name: Opciones PK_Opciones; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Opciones"
    ADD CONSTRAINT "PK_Opciones" PRIMARY KEY ("Id");


--
-- TOC entry 2939 (class 2606 OID 70003)
-- Name: OpcionesVoF PK_OpcionesVoF; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."OpcionesVoF"
    ADD CONSTRAINT "PK_OpcionesVoF" PRIMARY KEY ("Id");


--
-- TOC entry 2859 (class 2606 OID 69617)
-- Name: Persona PK_Persona; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Persona"
    ADD CONSTRAINT "PK_Persona" PRIMARY KEY ("Id");


--
-- TOC entry 2865 (class 2606 OID 69644)
-- Name: Preguntas PK_Preguntas; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Preguntas"
    ADD CONSTRAINT "PK_Preguntas" PRIMARY KEY ("Id");


--
-- TOC entry 2936 (class 2606 OID 69983)
-- Name: RespuestaDesarrollo PK_RespuestaDesarrollo; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaDesarrollo"
    ADD CONSTRAINT "PK_RespuestaDesarrollo" PRIMARY KEY ("Id");


--
-- TOC entry 2944 (class 2606 OID 70015)
-- Name: RespuestaVoF PK_RespuestaVoF; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaVoF"
    ADD CONSTRAINT "PK_RespuestaVoF" PRIMARY KEY ("Id");


--
-- TOC entry 2927 (class 2606 OID 69938)
-- Name: Respuestas PK_Respuestas; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Respuestas"
    ADD CONSTRAINT "PK_Respuestas" PRIMARY KEY ("CuentaId", "OpcionId");


--
-- TOC entry 2862 (class 2606 OID 69629)
-- Name: SeccionTemplate PK_SeccionTemplate; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."SeccionTemplate"
    ADD CONSTRAINT "PK_SeccionTemplate" PRIMARY KEY ("Id");


--
-- TOC entry 2924 (class 2606 OID 69928)
-- Name: VerdaderoFalso PK_VerdaderoFalso; Type: CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."VerdaderoFalso"
    ADD CONSTRAINT "PK_VerdaderoFalso" PRIMARY KEY ("Id");


--
-- TOC entry 2915 (class 1259 OID 70031)
-- Name: IX_Calificaciones_EstudianteId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Calificaciones_EstudianteId" ON bdARemplazar."Calificaciones" USING btree ("EstudianteId");


--
-- TOC entry 2916 (class 1259 OID 70032)
-- Name: IX_Calificaciones_EvaluacionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Calificaciones_EvaluacionId" ON bdARemplazar."Calificaciones" USING btree ("EvaluacionId");


--
-- TOC entry 2866 (class 1259 OID 70033)
-- Name: IX_Chats_Persona1Id; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Chats_Persona1Id" ON bdARemplazar."Chats" USING btree ("Persona1Id");


--
-- TOC entry 2867 (class 1259 OID 70034)
-- Name: IX_Chats_Persona2Id; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Chats_Persona2Id" ON bdARemplazar."Chats" USING btree ("Persona2Id");


--
-- TOC entry 2928 (class 1259 OID 70035)
-- Name: IX_Comentarios_ComentarioId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Comentarios_ComentarioId" ON bdARemplazar."Comentarios" USING btree ("ComentarioId");


--
-- TOC entry 2929 (class 1259 OID 70036)
-- Name: IX_Comentarios_CuentaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Comentarios_CuentaId" ON bdARemplazar."Comentarios" USING btree ("CuentaId");


--
-- TOC entry 2930 (class 1259 OID 70037)
-- Name: IX_Comentarios_DiscusionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Comentarios_DiscusionId" ON bdARemplazar."Comentarios" USING btree ("DiscusionId");


--
-- TOC entry 2898 (class 1259 OID 70038)
-- Name: IX_ComunicadoCurso_CursoId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_ComunicadoCurso_CursoId" ON bdARemplazar."ComunicadoCurso" USING btree ("CursoId");


--
-- TOC entry 2899 (class 1259 OID 70039)
-- Name: IX_ComunicadoCurso_DocenteId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_ComunicadoCurso_DocenteId" ON bdARemplazar."ComunicadoCurso" USING btree ("DocenteId");


--
-- TOC entry 2902 (class 1259 OID 70041)
-- Name: IX_CuentaGoogle_CuentaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE UNIQUE INDEX "IX_CuentaGoogle_CuentaId" ON bdARemplazar."CuentaGoogle" USING btree ("CuentaId");


--
-- TOC entry 2872 (class 1259 OID 70040)
-- Name: IX_Cuenta_PersonaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Cuenta_PersonaId" ON bdARemplazar."Cuenta" USING btree ("PersonaId");


--
-- TOC entry 2919 (class 1259 OID 70042)
-- Name: IX_Desarrollo_EvaluacionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Desarrollo_EvaluacionId" ON bdARemplazar."Desarrollo" USING btree ("EvaluacionId");


--
-- TOC entry 2905 (class 1259 OID 70043)
-- Name: IX_Discusiones_CuentaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Discusiones_CuentaId" ON bdARemplazar."Discusiones" USING btree ("CuentaId");


--
-- TOC entry 2906 (class 1259 OID 70044)
-- Name: IX_Discusiones_ForoId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Discusiones_ForoId" ON bdARemplazar."Discusiones" USING btree ("ForoId");


--
-- TOC entry 2909 (class 1259 OID 70045)
-- Name: IX_DocentesCurso_DocenteId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_DocentesCurso_DocenteId" ON bdARemplazar."DocentesCurso" USING btree ("DocenteId");


--
-- TOC entry 2878 (class 1259 OID 70046)
-- Name: IX_EncuestaCurso_CursoId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_EncuestaCurso_CursoId" ON bdARemplazar."EncuestaCurso" USING btree ("CursoId");


--
-- TOC entry 2879 (class 1259 OID 70047)
-- Name: IX_EncuestaCurso_EncuestaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE UNIQUE INDEX "IX_EncuestaCurso_EncuestaId" ON bdARemplazar."EncuestaCurso" USING btree ("EncuestaId");


--
-- TOC entry 2882 (class 1259 OID 70048)
-- Name: IX_Evaluaciones_SeccionTemplateId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Evaluaciones_SeccionTemplateId" ON bdARemplazar."Evaluaciones" USING btree ("SeccionTemplateId");


--
-- TOC entry 2885 (class 1259 OID 70049)
-- Name: IX_Informacion_SeccionTemplateId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Informacion_SeccionTemplateId" ON bdARemplazar."Informacion" USING btree ("SeccionTemplateId");


--
-- TOC entry 2912 (class 1259 OID 70050)
-- Name: IX_Inscripcion_EsudianteInscripcionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Inscripcion_EsudianteInscripcionId" ON bdARemplazar."Inscripcion" USING btree ("EsudianteInscripcionId");


--
-- TOC entry 2888 (class 1259 OID 70051)
-- Name: IX_Material_SeccionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Material_SeccionId" ON bdARemplazar."Material" USING btree ("SeccionId");


--
-- TOC entry 2894 (class 1259 OID 70052)
-- Name: IX_Mensajes_ChatId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Mensajes_ChatId" ON bdARemplazar."Mensajes" USING btree ("ChatId");


--
-- TOC entry 2895 (class 1259 OID 70053)
-- Name: IX_Mensajes_PersonaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Mensajes_PersonaId" ON bdARemplazar."Mensajes" USING btree ("PersonaId");


--
-- TOC entry 2875 (class 1259 OID 70054)
-- Name: IX_Notificaciones_PersonaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Notificaciones_PersonaId" ON bdARemplazar."Notificaciones" USING btree ("PersonaId");


--
-- TOC entry 2937 (class 1259 OID 70056)
-- Name: IX_OpcionesVoF_VerdaderoFalsoId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_OpcionesVoF_VerdaderoFalsoId" ON bdARemplazar."OpcionesVoF" USING btree ("VerdaderoFalsoId");


--
-- TOC entry 2891 (class 1259 OID 70055)
-- Name: IX_Opciones_PreguntaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Opciones_PreguntaId" ON bdARemplazar."Opciones" USING btree ("PreguntaId");


--
-- TOC entry 2863 (class 1259 OID 70057)
-- Name: IX_Preguntas_EncuestaId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Preguntas_EncuestaId" ON bdARemplazar."Preguntas" USING btree ("EncuestaId");


--
-- TOC entry 2933 (class 1259 OID 70058)
-- Name: IX_RespuestaDesarrollo_DesarrolloId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_RespuestaDesarrollo_DesarrolloId" ON bdARemplazar."RespuestaDesarrollo" USING btree ("DesarrolloId");


--
-- TOC entry 2934 (class 1259 OID 70059)
-- Name: IX_RespuestaDesarrollo_EstudianteId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_RespuestaDesarrollo_EstudianteId" ON bdARemplazar."RespuestaDesarrollo" USING btree ("EstudianteId");


--
-- TOC entry 2940 (class 1259 OID 70061)
-- Name: IX_RespuestaVoF_EstudianteId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_RespuestaVoF_EstudianteId" ON bdARemplazar."RespuestaVoF" USING btree ("EstudianteId");


--
-- TOC entry 2941 (class 1259 OID 70062)
-- Name: IX_RespuestaVoF_OpcionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_RespuestaVoF_OpcionId" ON bdARemplazar."RespuestaVoF" USING btree ("OpcionId");


--
-- TOC entry 2942 (class 1259 OID 70063)
-- Name: IX_RespuestaVoF_VerdaderoFalsoId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_RespuestaVoF_VerdaderoFalsoId" ON bdARemplazar."RespuestaVoF" USING btree ("VerdaderoFalsoId");


--
-- TOC entry 2925 (class 1259 OID 70060)
-- Name: IX_Respuestas_OpcionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_Respuestas_OpcionId" ON bdARemplazar."Respuestas" USING btree ("OpcionId");


--
-- TOC entry 2860 (class 1259 OID 70064)
-- Name: IX_SeccionTemplate_CursoId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_SeccionTemplate_CursoId" ON bdARemplazar."SeccionTemplate" USING btree ("CursoId");


--
-- TOC entry 2922 (class 1259 OID 70065)
-- Name: IX_VerdaderoFalso_EvaluacionId; Type: INDEX; Schema: bdARemplazar; Owner: postgres
--

CREATE INDEX "IX_VerdaderoFalso_EvaluacionId" ON bdARemplazar."VerdaderoFalso" USING btree ("EvaluacionId");


--
-- TOC entry 2969 (class 2606 OID 69894)
-- Name: Calificaciones FK_Calificaciones_Cuenta_EstudianteId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Calificaciones"
    ADD CONSTRAINT "FK_Calificaciones_Cuenta_EstudianteId" FOREIGN KEY ("EstudianteId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2970 (class 2606 OID 69899)
-- Name: Calificaciones FK_Calificaciones_Evaluaciones_EvaluacionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Calificaciones"
    ADD CONSTRAINT "FK_Calificaciones_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES bdARemplazar."Evaluaciones"("Id") ON DELETE CASCADE;


--
-- TOC entry 2947 (class 2606 OID 69657)
-- Name: Chats FK_Chats_Persona_Persona1Id; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Chats"
    ADD CONSTRAINT "FK_Chats_Persona_Persona1Id" FOREIGN KEY ("Persona1Id") REFERENCES bdARemplazar."Persona"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2948 (class 2606 OID 69662)
-- Name: Chats FK_Chats_Persona_Persona2Id; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Chats"
    ADD CONSTRAINT "FK_Chats_Persona_Persona2Id" FOREIGN KEY ("Persona2Id") REFERENCES bdARemplazar."Persona"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2975 (class 2606 OID 69959)
-- Name: Comentarios FK_Comentarios_Comentarios_ComentarioId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Comentarios"
    ADD CONSTRAINT "FK_Comentarios_Comentarios_ComentarioId" FOREIGN KEY ("ComentarioId") REFERENCES bdARemplazar."Comentarios"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2976 (class 2606 OID 69964)
-- Name: Comentarios FK_Comentarios_Cuenta_CuentaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Comentarios"
    ADD CONSTRAINT "FK_Comentarios_Cuenta_CuentaId" FOREIGN KEY ("CuentaId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2977 (class 2606 OID 69969)
-- Name: Comentarios FK_Comentarios_Discusiones_DiscusionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Comentarios"
    ADD CONSTRAINT "FK_Comentarios_Discusiones_DiscusionId" FOREIGN KEY ("DiscusionId") REFERENCES bdARemplazar."Discusiones"("Id") ON DELETE CASCADE;


--
-- TOC entry 2961 (class 2606 OID 69814)
-- Name: ComunicadoCurso FK_ComunicadoCurso_Cuenta_DocenteId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."ComunicadoCurso"
    ADD CONSTRAINT "FK_ComunicadoCurso_Cuenta_DocenteId" FOREIGN KEY ("DocenteId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2960 (class 2606 OID 69809)
-- Name: ComunicadoCurso FK_ComunicadoCurso_Curso_CursoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."ComunicadoCurso"
    ADD CONSTRAINT "FK_ComunicadoCurso_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES bdARemplazar."Curso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2962 (class 2606 OID 69829)
-- Name: CuentaGoogle FK_CuentaGoogle_Cuenta_CuentaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."CuentaGoogle"
    ADD CONSTRAINT "FK_CuentaGoogle_Cuenta_CuentaId" FOREIGN KEY ("CuentaId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2949 (class 2606 OID 69679)
-- Name: Cuenta FK_Cuenta_Persona_PersonaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Cuenta"
    ADD CONSTRAINT "FK_Cuenta_Persona_PersonaId" FOREIGN KEY ("PersonaId") REFERENCES bdARemplazar."Persona"("Id") ON DELETE CASCADE;


--
-- TOC entry 2971 (class 2606 OID 69914)
-- Name: Desarrollo FK_Desarrollo_Evaluaciones_EvaluacionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Desarrollo"
    ADD CONSTRAINT "FK_Desarrollo_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES bdARemplazar."Evaluaciones"("Id") ON DELETE CASCADE;


--
-- TOC entry 2963 (class 2606 OID 69844)
-- Name: Discusiones FK_Discusiones_Cuenta_CuentaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Discusiones"
    ADD CONSTRAINT "FK_Discusiones_Cuenta_CuentaId" FOREIGN KEY ("CuentaId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2964 (class 2606 OID 69849)
-- Name: Discusiones FK_Discusiones_Foros_ForoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Discusiones"
    ADD CONSTRAINT "FK_Discusiones_Foros_ForoId" FOREIGN KEY ("ForoId") REFERENCES bdARemplazar."Foros"("Id") ON DELETE CASCADE;


--
-- TOC entry 2966 (class 2606 OID 69864)
-- Name: DocentesCurso FK_DocentesCurso_Cuenta_DocenteId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."DocentesCurso"
    ADD CONSTRAINT "FK_DocentesCurso_Cuenta_DocenteId" FOREIGN KEY ("DocenteId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2965 (class 2606 OID 69859)
-- Name: DocentesCurso FK_DocentesCurso_Curso_CursoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."DocentesCurso"
    ADD CONSTRAINT "FK_DocentesCurso_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES bdARemplazar."Curso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2951 (class 2606 OID 69704)
-- Name: EncuestaCurso FK_EncuestaCurso_Curso_CursoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."EncuestaCurso"
    ADD CONSTRAINT "FK_EncuestaCurso_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES bdARemplazar."Curso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2952 (class 2606 OID 69709)
-- Name: EncuestaCurso FK_EncuestaCurso_Encuesta_EncuestaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."EncuestaCurso"
    ADD CONSTRAINT "FK_EncuestaCurso_Encuesta_EncuestaId" FOREIGN KEY ("EncuestaId") REFERENCES bdARemplazar."Encuesta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2953 (class 2606 OID 69714)
-- Name: EncuestaCurso FK_EncuestaCurso_SeccionTemplate_SeccionTemplateId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."EncuestaCurso"
    ADD CONSTRAINT "FK_EncuestaCurso_SeccionTemplate_SeccionTemplateId" FOREIGN KEY ("SeccionTemplateId") REFERENCES bdARemplazar."SeccionTemplate"("Id") ON DELETE CASCADE;


--
-- TOC entry 2954 (class 2606 OID 69729)
-- Name: Evaluaciones FK_Evaluaciones_SeccionTemplate_SeccionTemplateId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Evaluaciones"
    ADD CONSTRAINT "FK_Evaluaciones_SeccionTemplate_SeccionTemplateId" FOREIGN KEY ("SeccionTemplateId") REFERENCES bdARemplazar."SeccionTemplate"("Id") ON DELETE CASCADE;


--
-- TOC entry 2955 (class 2606 OID 69744)
-- Name: Informacion FK_Informacion_SeccionTemplate_SeccionTemplateId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Informacion"
    ADD CONSTRAINT "FK_Informacion_SeccionTemplate_SeccionTemplateId" FOREIGN KEY ("SeccionTemplateId") REFERENCES bdARemplazar."SeccionTemplate"("Id") ON DELETE CASCADE;


--
-- TOC entry 2968 (class 2606 OID 69879)
-- Name: Inscripcion FK_Inscripcion_Cuenta_EsudianteInscripcionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Inscripcion"
    ADD CONSTRAINT "FK_Inscripcion_Cuenta_EsudianteInscripcionId" FOREIGN KEY ("EsudianteInscripcionId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2967 (class 2606 OID 69874)
-- Name: Inscripcion FK_Inscripcion_Curso_CursoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Inscripcion"
    ADD CONSTRAINT "FK_Inscripcion_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES bdARemplazar."Curso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2956 (class 2606 OID 69759)
-- Name: Material FK_Material_SeccionTemplate_SeccionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Material"
    ADD CONSTRAINT "FK_Material_SeccionTemplate_SeccionId" FOREIGN KEY ("SeccionId") REFERENCES bdARemplazar."SeccionTemplate"("Id") ON DELETE CASCADE;


--
-- TOC entry 2958 (class 2606 OID 69789)
-- Name: Mensajes FK_Mensajes_Chats_ChatId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Mensajes"
    ADD CONSTRAINT "FK_Mensajes_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES bdARemplazar."Chats"("Id") ON DELETE CASCADE;


--
-- TOC entry 2959 (class 2606 OID 69794)
-- Name: Mensajes FK_Mensajes_Persona_PersonaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Mensajes"
    ADD CONSTRAINT "FK_Mensajes_Persona_PersonaId" FOREIGN KEY ("PersonaId") REFERENCES bdARemplazar."Persona"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2950 (class 2606 OID 69694)
-- Name: Notificaciones FK_Notificaciones_Persona_PersonaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Notificaciones"
    ADD CONSTRAINT "FK_Notificaciones_Persona_PersonaId" FOREIGN KEY ("PersonaId") REFERENCES bdARemplazar."Persona"("Id") ON DELETE CASCADE;


--
-- TOC entry 2980 (class 2606 OID 70004)
-- Name: OpcionesVoF FK_OpcionesVoF_VerdaderoFalso_VerdaderoFalsoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."OpcionesVoF"
    ADD CONSTRAINT "FK_OpcionesVoF_VerdaderoFalso_VerdaderoFalsoId" FOREIGN KEY ("VerdaderoFalsoId") REFERENCES bdARemplazar."VerdaderoFalso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2957 (class 2606 OID 69774)
-- Name: Opciones FK_Opciones_Preguntas_PreguntaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Opciones"
    ADD CONSTRAINT "FK_Opciones_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES bdARemplazar."Preguntas"("Id") ON DELETE CASCADE;


--
-- TOC entry 2946 (class 2606 OID 69645)
-- Name: Preguntas FK_Preguntas_Encuesta_EncuestaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Preguntas"
    ADD CONSTRAINT "FK_Preguntas_Encuesta_EncuestaId" FOREIGN KEY ("EncuestaId") REFERENCES bdARemplazar."Encuesta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2979 (class 2606 OID 69989)
-- Name: RespuestaDesarrollo FK_RespuestaDesarrollo_Cuenta_EstudianteId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaDesarrollo"
    ADD CONSTRAINT "FK_RespuestaDesarrollo_Cuenta_EstudianteId" FOREIGN KEY ("EstudianteId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2978 (class 2606 OID 69984)
-- Name: RespuestaDesarrollo FK_RespuestaDesarrollo_Desarrollo_DesarrolloId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaDesarrollo"
    ADD CONSTRAINT "FK_RespuestaDesarrollo_Desarrollo_DesarrolloId" FOREIGN KEY ("DesarrolloId") REFERENCES bdARemplazar."Desarrollo"("Id") ON DELETE CASCADE;


--
-- TOC entry 2981 (class 2606 OID 70016)
-- Name: RespuestaVoF FK_RespuestaVoF_Cuenta_EstudianteId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaVoF"
    ADD CONSTRAINT "FK_RespuestaVoF_Cuenta_EstudianteId" FOREIGN KEY ("EstudianteId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2982 (class 2606 OID 70021)
-- Name: RespuestaVoF FK_RespuestaVoF_OpcionesVoF_OpcionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaVoF"
    ADD CONSTRAINT "FK_RespuestaVoF_OpcionesVoF_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES bdARemplazar."OpcionesVoF"("Id") ON DELETE CASCADE;


--
-- TOC entry 2983 (class 2606 OID 70026)
-- Name: RespuestaVoF FK_RespuestaVoF_VerdaderoFalso_VerdaderoFalsoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."RespuestaVoF"
    ADD CONSTRAINT "FK_RespuestaVoF_VerdaderoFalso_VerdaderoFalsoId" FOREIGN KEY ("VerdaderoFalsoId") REFERENCES bdARemplazar."VerdaderoFalso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2973 (class 2606 OID 69939)
-- Name: Respuestas FK_Respuestas_Cuenta_CuentaId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Respuestas"
    ADD CONSTRAINT "FK_Respuestas_Cuenta_CuentaId" FOREIGN KEY ("CuentaId") REFERENCES bdARemplazar."Cuenta"("Id") ON DELETE CASCADE;


--
-- TOC entry 2974 (class 2606 OID 69944)
-- Name: Respuestas FK_Respuestas_Opciones_OpcionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."Respuestas"
    ADD CONSTRAINT "FK_Respuestas_Opciones_OpcionId" FOREIGN KEY ("OpcionId") REFERENCES bdARemplazar."Opciones"("Id") ON DELETE CASCADE;


--
-- TOC entry 2945 (class 2606 OID 69630)
-- Name: SeccionTemplate FK_SeccionTemplate_Curso_CursoId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."SeccionTemplate"
    ADD CONSTRAINT "FK_SeccionTemplate_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES bdARemplazar."Curso"("Id") ON DELETE CASCADE;


--
-- TOC entry 2972 (class 2606 OID 69929)
-- Name: VerdaderoFalso FK_VerdaderoFalso_Evaluaciones_EvaluacionId; Type: FK CONSTRAINT; Schema: bdARemplazar; Owner: postgres
--

ALTER TABLE ONLY bdARemplazar."VerdaderoFalso"
    ADD CONSTRAINT "FK_VerdaderoFalso_Evaluaciones_EvaluacionId" FOREIGN KEY ("EvaluacionId") REFERENCES bdARemplazar."Evaluaciones"("Id") ON DELETE CASCADE;


-- Completed on 2020-11-13 21:13:50

--
-- PostgreSQL database dump complete
--

